/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primer.programa;

/**
 *
 * @author DELL 3467
 */
public class opcion extends javax.swing.JFrame {

    /**
     * Creates new form opcion
     */
    public opcion() {
        initComponents();

        this.setLocationRelativeTo(null);
    }
     
            public void run() {
                new opcion().setVisible(true);
    
            }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tdex1 = new javax.swing.JPanel();
        extj2 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        tile = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        x = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdex1.setBackground(new java.awt.Color(255, 255, 255));
        tdex1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        tdex1.setForeground(new java.awt.Color(0, 0, 0));
        tdex1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout tdex1Layout = new javax.swing.GroupLayout(tdex1);
        tdex1.setLayout(tdex1Layout);
        tdex1Layout.setHorizontalGroup(
            tdex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        tdex1Layout.setVerticalGroup(
            tdex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        getContentPane().add(tdex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 240, 20));

        extj2.setBackground(new java.awt.Color(255, 255, 255));
        extj2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        extj2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout extj2Layout = new javax.swing.GroupLayout(extj2);
        extj2.setLayout(extj2Layout);
        extj2Layout.setHorizontalGroup(
            extj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        extj2Layout.setVerticalGroup(
            extj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        getContentPane().add(extj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, 20));

        title2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title2.setForeground(new java.awt.Color(102, 0, 0));
        title2.setText("JUGADOR 2");
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 20));

        tile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tile.setForeground(new java.awt.Color(102, 0, 0));
        tile.setText(" JUGADOR 1");
        getContentPane().add(tile, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("jugar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(153, 0, 0), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 90, -1));

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon_Red_X.png"))); // NOI18N
        x.setText("jLabel4");
        getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -10, 230, 160));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("    O");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("    X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 60, 50));

        o.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uppercase-o-hi.png"))); // NOI18N
        o.setText("jLabel5");
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 520, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WHDQ-513996549.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        spend reg=new spend();
        reg.setTitle("a jugar");
        reg.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extj2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel o;
    private javax.swing.JPanel tdex1;
    private javax.swing.JLabel tile;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
