/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electproy;

import  javax.swing.JOptionPane;

/**
 *
 * @author DELL 3467
 */
public class pant extends javax.swing.JFrame {
    

    public pant() {
        initComponents();
    }
    /**public static int res (int num1,int num2){
    int k;
    k=num2-num1;
     return k;
    }
     public static int div (int num1,int num2){
    int q;
    q=num1/num2;
     return q;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LECTANT = new javax.swing.JTextField();
        DAYCONS = new javax.swing.JTextField();
        LECTACT1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 0, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("         LECTURA ANTERIOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 150, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("      LECTURA ACTUAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  DIAS CONSUMIDO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, 20));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 40, -1));

        LECTANT.setBackground(new java.awt.Color(20, 5, 3));
        LECTANT.setForeground(new java.awt.Color(255, 255, 255));
        LECTANT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        LECTANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LECTANTActionPerformed(evt);
            }
        });
        getContentPane().add(LECTANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, -1));

        DAYCONS.setBackground(new java.awt.Color(10, 4, 4));
        DAYCONS.setForeground(new java.awt.Color(255, 255, 255));
        DAYCONS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        DAYCONS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAYCONSActionPerformed(evt);
            }
        });
        getContentPane().add(DAYCONS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, -1));

        LECTACT1.setBackground(new java.awt.Color(20, 5, 3));
        LECTACT1.setForeground(new java.awt.Color(255, 255, 255));
        LECTACT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        LECTACT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LECTACT1ActionPerformed(evt);
            }
        });
        getContentPane().add(LECTACT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon-user.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WHDQ-513996549.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LECTANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LECTANTActionPerformed
              

    }//GEN-LAST:event_LECTANTActionPerformed

    private void DAYCONSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAYCONSActionPerformed

    }//GEN-LAST:event_DAYCONSActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    float valant1;
    float valant2; 
    float valant3;
    float calc;
    float rest;
    float div; 
    float mult;
       
       valant3 = Integer.parseInt(DAYCONS.getText());       
       valant2 = Integer.parseInt(LECTANT.getText());
       valant1 = Integer.parseInt(LECTACT1.getText());
      
        String valoff;
        /**int k,q,op;
        k=res(valant1,valant2);
        q=div(k,valant3);
        op=q*30;
        valoff=Integer.toString(op);*/
        rest=valant1-valant2;
        System.out.println(""+rest);
        div=rest/valant3;
        System.out.println(""+div);
        mult=div*30;
        calc=mult;
        System.out.println(""+calc);
        valoff=Integer.toString((int) calc);
     JOptionPane.showMessageDialog(this,"lo consumido es"+valoff); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LECTACT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LECTACT1ActionPerformed
       
 
    }//GEN-LAST:event_LECTACT1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DAYCONS;
    private javax.swing.JTextField LECTACT1;
    private javax.swing.JTextField LECTANT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
